---
- name: Ensure digitalocean firewalls
  tags:
    - digitalocean
    - digitalocean_firewalls
  block:
    - name: Ensure digitalocean firewalls
      ansible.builtin.import_tasks: digitalocean_firewalls.yml
