---
argument_specs:
  main:
    options:
      digitalocean_droplets:
        type: list
        required: true
        elements: dict
        options:
          name:
            required: true
            type: str
          region:
            required: true
            type: str
          size:
            required: true
            type: str
          image:
            required: true
            type: str
          base_url:
            type: str
          oauth_token:
            type: str
          state:
            type: str
            choices:
              - present
              - absent
              - active
              - inactive
          tags:
            type: list
            elements: dict
            options:
              name:
                type: str
              state:
                type: str
                choices:
                  - present
                  - absent
          firewall:
            type: list
            elements: str
          ssh_keys:
            required: true
            type: list
            elements: str
          ipv6:
            type: bool
          monitoring:
            type: bool
