---
galaxy_info:
  author: Roman Kuzmitskii <ansible@damex.org>
  description: digitalocean droplets role
  license: GPLv2
  min_ansible_version: 2.12.0
  galaxy_tags: []
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - focal
dependencies:
  - role: damex.digitalocean.digitalocean_sshkeys
