---
argument_specs:
  main:
    options:
      digitalocean_firewalls:
        type: list
        required: true
        elements: dict
        options:
          name:
            required: true
            type: str
          inbound_rules:
            required: true
            type: str
          outbound_rules:
            required: true
            type: str
          base_url:
            type: str
          oauth_token:
            type: str
          state:
            type: str
            choices:
              - present
              - absent
          tags:
            type: list
            elements: str
