---
- name: Ensure digitalocean sshkeys facts
  community.digitalocean.digital_ocean_sshkey_info:
    oauth_token: "{{ digitalocean_sshkeys_oauth_token | default(omit) }}"
  register: digitalocean_sshkeys_facts
