---
galaxy_info:
  author: Roman Kuzmitskii <ansible@damex.org>
  description: digitalocean tags role
  license: GPLv2
  min_ansible_version: 2.16.0
  galaxy_tags: []
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - focal
dependencies: []
