---
- name: ensure digitalocean droplet sshkeys ids
  ansible.builtin.set_fact:
    digitalocean_droplet_ssh_keys_ids: "{{ digitalocean_droplet_ssh_keys_ids | default([]) + digitalocean_sshkeys_facts.data | selectattr('name', 'match', digitalocean_droplet_ssh_key) | map(attribute='id') }}"
  failed_when: not digitalocean_sshkeys_facts.data | selectattr('name', 'match', digitalocean_droplet_ssh_key)
  loop: "{{ digitalocean_droplet_ssh_keys }}"
  loop_control:
    loop_var: digitalocean_droplet_ssh_key

- name: ensure digitalocean droplet
  community.digitalocean.digital_ocean_droplet:
    name: "{{ digitalocean_droplet_name }}"
    id: "{{ digitalocean_droplets_facts.data | selectattr('name', 'match', digitalocean_droplet_name) | map(attribute='id') | join }}"
    region: "{{ digitalocean_droplet_region }}"
    baseurl: "{{ digitalocean_droplet_baseurl | default(omit) }}"
    oauth_token: "{{ digitalocean_droplet_oauth_token }}"
    size: "{{ digitalocean_droplet_size }}"
    image: "{{ digitalocean_droplet_image }}"
    unique_name: true
    firewall: "{{ digitalocean_droplet_firewall | default(omit) }}"
    ssh_keys: "{{ digitalocean_droplet_ssh_keys_ids }}"
    monitoring: "{{ digitalocean_droplet_monitoring }}"
    state: "{{ digitalocean_droplet_state }}"
    tags: "{{ digitalocean_droplet_tags }}"
