---
- name: Ensure digitalocean droplet sshkeys ids
  ansible.builtin.set_fact:
    digitalocean_droplet_ssh_keys_ids: "{{ digitalocean_droplet_ssh_keys_ids | default([]) + digitalocean_sshkeys_facts.data | selectattr('name', 'match', digitalocean_droplet_ssh_key) | map(attribute='id') }}"
  failed_when: not digitalocean_sshkeys_facts.data | selectattr('name', 'match', digitalocean_droplet_ssh_key)
  loop: "{{ digitalocean_droplet_ssh_keys }}"
  loop_control:
    loop_var: digitalocean_droplet_ssh_key

- name: Ensure digitalocean droplet facts
  ansible.builtin.set_fact:
    digitalocean_droplet_id: "{{ digitalocean_droplets_facts.data | selectattr('name', 'match', digitalocean_droplet_name) | map(attribute='id') | join }}"
  when: digitalocean_droplets_facts.data

- name: Ensure digitalocean droplet
  community.digitalocean.digital_ocean_droplet:
    name: "{{ digitalocean_droplet_name }}"
    id: "{{ digitalocean_droplet_id | default(omit) }}"
    region: "{{ digitalocean_droplet_region }}"
    baseurl: "{{ digitalocean_droplet_baseurl | default(omit) }}"
    oauth_token: "{{ digitalocean_droplet_oauth_token | default(omit) }}"
    size: "{{ digitalocean_droplet_size }}"
    image: "{{ digitalocean_droplet_image }}"
    unique_name: true
    firewall: "{{ digitalocean_droplet_firewall | default(omit) }}"
    ssh_keys: "{{ digitalocean_droplet_ssh_keys_ids }}"
    ipv6: "{{ digitalocean_droplet_ipv6 }}"
    monitoring: "{{ digitalocean_droplet_monitoring }}"
    state: "{{ digitalocean_droplet_state }}"

- name: Ensure digitalocean droplet tags
  ansible.builtin.include_role:
    name: damex.digitalocean.digitalocean_tags
  vars:
    digitalocean_tags: # noqa: var-naming[no-role-prefix]
      - name: "{{ digitalocean_droplet_tag.name }}"
        resource_id: "{{ digitalocean_droplet_id | default(omit) }}"
        resource_type: droplet
        state: "{{ digitalocean_droplet_tag.name | default(digitalocean_droplet_state) }}"
  loop: "{{ digitalocean_droplet_tags }}"
  loop_control:
    loop_var: digitalocean_droplet_tag
