---
- name: Ensure digitalocean droplets facts
  community.digitalocean.digital_ocean_droplet_info:
    oauth_token: "{{ digitalocean_droplets_oauth_token | default(omit) }}"
  register: digitalocean_droplets_facts
