---
- name: ensure digitalocean droplets
  block:
    - name: ensure digitalocean droplets facts
      ansible.builtin.import_tasks: digitalocean_droplets_facts.yml
    - name: ensure digitalocean droplets
      ansible.builtin.import_tasks: digitalocean_droplets.yml
  tags:
    - digitalocean
    - digitalocean_droplets
